apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: gc-example-a
    version: v2
  name: gc-example-a-v2
  namespace: grupo-conocimiento
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gc-example-a
        version: v2
    spec:
      containers:
      - image: gcr.io/gke-inigo-1-229519/gc-example-a:2.0.0
        imagePullPolicy: IfNotPresent
        name: gc-example-a
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30